spring.application.name=spring-secu-demo

spring.security.user.name=sujan
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict


spring.datasource.url = jdbc:postgresql://localhost:5433/SujanDB
spring.datasource.username = postgres
spring.datasource.password = 41829
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
